import "~/styles/globals.css";

import { SidebarInset, SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar"
import { AppSidebar } from '~/components/app-sidebar'

import { cookies } from "next/headers"


import type { Metadata } from 'next'


import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignIn
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

import { CSSProperties } from 'react';

interface CustomCSSProperties extends CSSProperties {
  '--sidebar-width'?: string;
  '--sidebar-width-mobile'?: string;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <SidebarInset>
              <header className="flex justify-end items-center p-4 gap-4 h-12">
                <SignedOut>
                  <SignInButton />
                  <SignUpButton />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </header>
              
              <main className="w-full p-4 sm:px-6 sm:py-0 md:gap-8">
                <div className="container flex min-h-[calc(100vh-5.5rem)] w-full flex-col items-start space-y-4 px-2 sm:px-6 font-sans">
                  <SignedOut>
                    <SignIn />
                  </SignedOut>

                  <SignedIn>
                    {children}
                  </SignedIn>
                </div>
              </main>
            </SidebarInset>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
